language: shell
os:
  - windows
  - osx

install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install --no-progress -y wixtoolset; fi
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - source $TRAVIS_BUILD_DIR/install-jdk.sh --feature 11 --target $HOME/openjdk11
  - source $TRAVIS_BUILD_DIR/install-jdk.sh --feature 14 --target $HOME/openjdk14
  - export JAVA_HOME=$HOME/openjdk11
  - source $TRAVIS_BUILD_DIR/scripts/install_openjfx.sh

script:
  - export JAVA_HOME=$HOME/openjdk11
  - export BADASS_RUNTIME_JPACKAGE_HOME=$HOME/openjdk14
  - ./gradlew build jpackage
