language: shell

jobs:
  include:
    - os: windows
      install:
        - scripts/install_jdk_windows.sh
        - export JAVA_HOME=$HOME/jdk-13
        - export BADASS_RUNTIME_JPACKAGE_HOME=$HOME/jdk-14
        - bash -x ./scripts/install_openjfx.sh windows
    - os: osx
      install:
        - scripts/install_jdk_mac.sh
        - export JAVA_HOME=$HOME/jdk-13.jdk/Contents/Home
        - export BADASS_RUNTIME_JPACKAGE_HOME=$HOME/jdk-14.jdk/Contents/Home
        - bash -x ./scripts/install_openjfx.sh mac

script:
  - ./gradlew build jpackage
